services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=node-1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITITAL_ADMIN_PASSWORD=StrongPassword@123
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - os-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    restart: unless-stopped
    networks:
      - os-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    healthcheck:
      test: ["CMD-SHELL","curl -sSf http://localhost:5601/api/status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    restart: unless-stopped
    networks:
      - os-net

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    user: root
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - ./logs:/var/log/app:ro
    depends_on:
      opensearch:
        condition: service_healthy
      springboot-app:
        condition: service_started
    restart: unless-stopped
    networks:
      - os-net

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - LOGGING_FILE_PATH=/app/logs
    networks:
      - os-net

volumes:
  os-data:

networks:
  os-net:
    driver: bridge